---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-env
  labels:
    app: nginx
    purpose: svcdemo
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
     matchExpressions:
       - key: app
         operator: In
         values:
          - jenkins
          - hudson
       - key: release
         operator: Exists    
  template:
    metadata:
      labels:
        app: jenkins
        release: v1.1        
    spec: 
     containers:
      - name: nginx
        image: nginx:1.25
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: purpose
            value: learning
          - name: why
            value: dontknow