---
apiVersion: v1
kind: Service
metadata:
  name: svc-sample
  labels:
    app: nd
spec:
  type: NodePort
  selector:
    app: nginx
  Ports:
    targetport: 80
    containerPort: 8080
    nodePort: 32055
