---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: rs-sample
 labels:
   purpose: nginx
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      release: v1.1
  template:
    metadata:
      labels:
        app: nginx
        release: v1.1
    spec:
      containers:
         - name: rs-container
           image: nginx
           ports:
             - containerPort: 80
               protocol: TCP


      