---
apiVersion: v1
kind: Pod 
metadata:
  name: cm-s-demo
  labels:
    app: demo
spec:
  containers:
    - name: exp
      image: alpine
      args:
        - sleep
        - 1d
      envFrom:
        - configMapRef: cm-sample
      secretRef: 
        - name: cm-secret

